from datetime import date
from datetime import datetime
from datetime import timedelta
import time

logtime = datetime.now()

def plateau():
    print("It's a long walk. I should get back to you in you, in a minute.")
    time.sleep(30)
    print("Great, i am back. Good to know you waited for me. I finally reached the checkpoint.")
    print("Do you want to hear the good news or bad news?")
    print("I found part of my crew... Davies and Laurent.")
    print("Those are the bad news... They are dead.")

def pact():
    time.sleep(2)
    print("Great. Very well. I need you to help me navigate to the emergency Shuttle.")
    time.sleep(1)
    print("It detached 24km southwest from here, should take a few hours from where I stand.")
    print("My GPS is damaged..., but you should be able to guide me through this ecosystem.")
    time.sleep(1)
    print("I am walking towards my next destination...")
    time.sleep(2)
    print("I'll be uploading data profiles to you...")
    print("Not that it matters, this is futile information now...")
    time.sleep(3)
    
    print("Uploading Data...")
    print("............................")
    print("Name: Ernst, Klaus")
    print("Age: 50")
    print("Planet: Earth, CH")
    print("Duty: Biologist")
    print("Status: Dead")
    time.sleep(2)
    print("............................")
    print("Name: Fujin, Akira")
    print("Age: 29")
    print("Planet: Earth, JP")
    print("Duty: Geologist")
    print("Status: Dead")
    time.sleep(3)
    print("............................")
    print("Name: Davies, Emma")
    print("Age: 44")
    print("Planet: Earth, EN")
    print("Duty: Anthropologist")
    print("Status: Dead")
    time.sleep(3)
    print("............................")
    print("Name: Laurent, Martin")
    print("Age: 32")
    print("Planet: Earth, FR")
    print("Duty: Photo/Videographer ")
    print("Status: Dead")
    time.sleep(1)
    print("............................")
    print("Name: Diaz, Juan")
    print("Age: 29")
    print("Planet: Earth, ES")
    print("Duty: Documenter")
    print("Status: Alive")
    time.sleep(4)
    print("............................")
    print("Name: Salazar, Pedro")
    print("Age: 45")
    print("Planet: Earth, PT")
    print("Duty: Captain")
    print("Status: Alive")
    time.sleep(3)
    print("............................")
    print("Name: van Beek, Johannes")
    print("Age: 36")
    print("Planet: Earth, BE")
    print("Duty: Lead Research")
    print("Status: Dead")
    print("............................")
    time.sleep(2)
    print("Upload complete")
    time.sleep(4)
    print()
    print("Yes, the Captain is still missing...")
    time.sleep(2)
    print("I must find him, in order to leave this place.")
    time.sleep(5)
    print("Looks like I arrived to my checkpoint...")
    print("From here on, I should choose a route... The Cave or th Plateau? (Plateau / Cave)")
    act_two = input("")
    act_two = act_two.upper()
    if act_two == "PLATEAU" or act_one == "P" or act_one == "TAKE THE PLATEAU" or act_one == "GO TO THE PLATEAU":
            plateau()
    elif act_two == "CAVE" or act_two == "TAKE THE CAVE" or act_two == "GO INSIDE THE GAVE" or act_two == "GO THROUGH THE CAVE":
            cave()
            

def start():
    print('"Transmission accepted"')
    print("")
    print("Hello!")
    print("Who is this? What is your name? ")
    name = str(input(""))
    time.sleep(2)
    print("Finally... Somebody! You must be the assigned Operator, from Stationary division EPSILON.")
    time.sleep(1)
    print("I have been trying to contact you guys for days.")
    time.sleep(2)
    print(f"Listen " + name + " ... I am the deployed documenter, Diaz... I am the sole survivour of SIGMA-02, Planet 9 - Research team.")
    time.sleep(2)
    print("Me and my crew disembarked from Earth en route to Planet 9 two months ago, our ship GAMMA crashed...")
    time.sleep(3)
    print("A pick up vessel was supposed to dock this morning and pick us up... Except, it never landed...")
    print("There was another incident last week, I dont know what happened...")
    time.sleep(3)
    print("I woke dizzy in my pod and my team disapeared...")
    print("Crew status indicates they are dead, with the exception of the Captain...")
    time.sleep(1)
    print("Our internal hardware is damaged and I cannot salvage anything from our station...")
    print()
    
    print("Connection lost...")
    print("Reconnecting...")
    time.sleep(2)
    print("Reconnecting...")
    time.sleep(9)
    print("Connection established")
    print(logtime)
    print()
    
    print("Are you still here? The connection is weak here... It is imperative that you help me!")
    time.sleep(2)
    print("I need to get out of here. That is why they sent you right?")
    time.sleep(1)
    print("Can you stay online and help me? (Yes / No)")
    act_one = input("")
    act_one = act_one.upper()
    if act_one == "Y" or act_one == "YES" or act_one == "SURE" or act_one == "OFCOURSE" or act_one == "DEFINETLY":
            pact()
    elif act_one == "N" or act_one == "NO" or act_one == "NO WAY" or act_one == "SORRY" or act_one == "CAN'T HELP YOU":
            print("Call suspended")
            
            
print("............................................................................................")
time.sleep(2)
print(datetime.now() + timedelta(days=5, hours=-5))
print("Final report of Research Starship 'GAMMA'.")
time.sleep(2)
print("The other members of the Crew... are dead, the Captain is missing, the cargo and ship wrecked.")
print("I should reach the Emergency shuttle in a week.")
time.sleep(1)
print("With a little luck, the operator will accept my transmission call...")
time.sleep(4)
print("This is Diaz, the last survivor of startship GAMMA... logging off.")
print("............................................................................................")
time.sleep(5)
print(" ")
print(".̪̜̳͓̟.̳͎ͅ.̩̩̰...̭̗͕.̲͙.̜͇͈.̖..̺̟̬̠̞.̹͍̙.͈͙.̲̗̗͙.͙̩͍͇.̼͓̮̺.̯͖͚̞.͙̣̳͎..̲̫̱͇.͎͓̘...̙̦͓̭͙.̝ͅ.̩.̹͓ͅ.̳͇͕.̤̹.̮̥̻.̣̤̫.̻̞̯.̗͖̦̟̮.̖.̻.͍̱ͅ...̹͚͎.̗̜̞.̰.̙̩̲͍.̫̳̮̱.̱̰͕͉..̳.͓͖͖.̗.̞̮̣̰̣.͚̭.͓̩.̞͕̼ͅ.̼̫.̠͙̪..̰̤̙̗.̰̰̳.̺̬̜̯̰.̠͕͕̠.̠̭͖.͓͉̮̹.͔͕̮..̪.̤̯̘̭.͎̣̮.̫̯̫.͚̜̙.͚̦..͎̟.͇.̱̺.̰͖̖̗̠..̮..̫͚.̰ͅ.̥̜͙̫̘.̰͎͖.̹̼̞̤͈.̻̙͎.͕̗̼̺̬.̞̘...̲͈.̼̳..̦̖̣̳͈.")
print(" ")
print("                                                                                            ")
print("                                      ㄥㄖ丂ㄒ                                               ")
print("                                                                                            ")
print(" ")
print(".̪̜̳͓̟.̳͎ͅ.̩̩̰...̭̗͕.̲͙.̜͇͈.̖..̺̟̬̠̞.̹͍̙.͈͙.̲̗̗͙.͙̩͍͇.̼͓̮̺.̯͖͚̞.͙̣̳͎..̲̫̱͇.͎͓̘...̙̦͓̭͙.̝ͅ.̩.̹͓ͅ.̳͇͕.̤̹.̮̥̻.̣̤̫.̻̞̯.̗͖̦̟̮.̖.̻.͍̱ͅ...̹͚͎.̗̜̞.̰.̙̩̲͍.̫̳̮̱.̱̰͕͉..̳.͓͖͖.̗.̞̮̣̰̣.͚̭.͓̩.̞͕̼ͅ.̼̫.̠͙̪..̰̤̙̗.̰̰̳.̺̬̜̯̰.̠͕͕̠.̠̭͖.͓͉̮̹.͔͕̮..̪.̤̯̘̭.͎̣̮.̫̯̫.͚̜̙.͚̦..͎̟.͇.̱̺.̰͖̖̗̠..̮..̫͚.̰ͅ.̥̜͙̫̘.̰͎͖.̹̼̞̤͈.̻̙͎.͕̗̼̺̬.̞̘...̲͈.̼̳..̦̖̣̳͈.")
print(" ")
time.sleep(2)
print(" ")
print("Incoming signal...")
time.sleep(3)
print("Incoming signal...")
time.sleep(1)
print("Incoming signal...")
print("Connecting...")
time.sleep(0.3)
print("Connection established")
print(logtime)
print("EPSILON Station-P3, Mars")
print()
time.sleep(2)
print("Hello?")
time.sleep(1)
print("Hello?! Anybody there?")
print("")

print("Accept transmission? (Accept/Decline)") 
startgame = input("")
startgame = startgame.upper()
if startgame == "YES" or startgame == "Y" or startgame == "ACCEPT":
    start()
elif startgame == "NO" or startgame == "N" or startgame == "DECLINE":
    print("Call Declined")
